// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SwiftCart.Api.Data;

#nullable disable

namespace SwiftCart.Api.Data.Migrations
{
    [DbContext(typeof(SwiftCartDbContext))]
    [Migration("20260405070902_AddMallManagers")]
    partial class AddMallManagers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SwiftCart.Api.Models.Entities.AdminEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("admins", (string)null);
                });

            modelBuilder.Entity("SwiftCart.Api.Models.Entities.MallEntity", b =>
                {
                    b.Property<string>("MallId")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("mall_id");

                    b.Property<bool?>("Active")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active");

                    b.Property<string>("AreaCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("area_code");

                    b.Property<string>("City")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int?>("EstYear")
                        .HasColumnType("int")
                        .HasColumnName("est_year");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("MallCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("mall_code");

                    b.Property<int?>("MallNumber")
                        .HasColumnType("int")
                        .HasColumnName("mall_number");

                    b.Property<int>("MaxProducts")
                        .HasColumnType("int")
                        .HasColumnName("max_products");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("name");

                    b.Property<string>("OwnerEmail")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("owner_email");

                    b.Property<string>("OwnerName")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("owner_name");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("plan_type");

                    b.Property<string>("State")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("state");

                    b.Property<DateTime>("SubscriptionEndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("subscription_end_date");

                    b.Property<DateTime>("SubscriptionStartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("subscription_start_date");

                    b.HasKey("MallId");

                    b.ToTable("malls", (string)null);
                });

            modelBuilder.Entity("SwiftCart.Api.Models.Entities.MallManagerEntity", b =>
                {
                    b.Property<string>("ManagerId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("manager_id");

                    b.Property<string>("AssignedEmail")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("assigned_email");

                    b.Property<string>("AssignedUid")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("assigned_uid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LinkedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("linked_at");

                    b.Property<string>("MallId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("mall_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("PasswordUpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("password_updated_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("ManagerId");

                    b.HasIndex("MallId");

                    b.ToTable("mall_managers", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
