// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUCUOw0wiAc7R0JpShGakkYaSPLL8ZON0',
    appId: '1:877619186510:web:f3c42939648903cde66c1f',
    messagingSenderId: '877619186510',
    projectId: 'swiftcart-69c08',
    authDomain: 'swiftcart-69c08.firebaseapp.com',
    storageBucket: 'swiftcart-69c08.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjfqzJzLi5CHyybytnfSzRtZtn55vV8W0',
    appId: '1:877619186510:android:21c52e371c98688fe66c1f',
    messagingSenderId: '877619186510',
    projectId: 'swiftcart-69c08',
    storageBucket: 'swiftcart-69c08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa9ieQ1IpTmx4HT7XmbTfq-QDqwHo42fs',
    appId: '1:877619186510:ios:5ecd9591b11013a0e66c1f',
    messagingSenderId: '877619186510',
    projectId: 'swiftcart-69c08',
    storageBucket: 'swiftcart-69c08.firebasestorage.app',
    iosBundleId: 'com.example.swiftcartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa9ieQ1IpTmx4HT7XmbTfq-QDqwHo42fs',
    appId: '1:877619186510:ios:5ecd9591b11013a0e66c1f',
    messagingSenderId: '877619186510',
    projectId: 'swiftcart-69c08',
    storageBucket: 'swiftcart-69c08.firebasestorage.app',
    iosBundleId: 'com.example.swiftcartApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUCUOw0wiAc7R0JpShGakkYaSPLL8ZON0',
    appId: '1:877619186510:web:3ba91e4fa7e1dde0e66c1f',
    messagingSenderId: '877619186510',
    projectId: 'swiftcart-69c08',
    authDomain: 'swiftcart-69c08.firebaseapp.com',
    storageBucket: 'swiftcart-69c08.firebasestorage.app',
  );
}
